### PR TITLE
gSOAP version bump

### PR DESCRIPTION
**Pull request by Sheridan**
gSOAP 2.8.92 was removed from SourceForge

### CODE REVIEW

**Comment by mleeman** [comment]
I think, instead of bumping the gsoap version, it would be better to use the system libraries instead of a wget and compile.

**Comment by Sheridan** [comment]
Already done: https://github.com/Sheridan/onvif_srvd

But without PTZ yet

**Comment by mleeman** [comment]
@Sheridan I did the same thing while packaging it for Debian :-/ I'll have a look if I can sync your work with mine to have something similar.

**Comment by Sheridan** [comment]
I have more work done there, not just refusal to compile gsoap. Reworked object model, logging, service configuration in json file...

**Comment by mleeman** [comment]
Very nice; a modern build system, a JSON config file, ...

I added the debian package files, am now trying to get wsse working to get that windows discovery tool working.

**Comment by KoynovStas** [comment]
Thanks, but updating a version every time it's removed from SourceForge is bad practice IMHO. I found a repository where copies of the gSoap archives are saved: https://github.com/SrcBackup/gsoap. When I have time to test the new version, I will update it, (at least it makes sense for the problem described here: https://sourceforge.net/p/gsoap2/bugs/1269/), this problem was solved in version 2.8.99.

**Pull request closed without merging**
